/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedFarmsIndexRouteImport } from './routes/_authenticated/farms/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicManifestRouteImport } from './routes/api/public/manifest'
import { Route as AuthenticatedFarmsIdRouteImport } from './routes/_authenticated/farms/$id'
import { Route as AuthenticatedAdminVisionTestRouteImport } from './routes/_authenticated/admin/vision-test'
import { Route as AuthenticatedAdminVisionRouteImport } from './routes/_authenticated/admin/vision'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminResourcesRouteImport } from './routes/_authenticated/admin/resources'
import { Route as AuthenticatedAdminRecoveryRouteImport } from './routes/_authenticated/admin/recovery'
import { Route as AuthenticatedAdminMonitoringRouteImport } from './routes/_authenticated/admin/monitoring'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin/logs'
import { Route as AuthenticatedAdminFleetsRouteImport } from './routes/_authenticated/admin/fleets'
import { Route as AuthenticatedAdminFarmsRouteImport } from './routes/_authenticated/admin/farms'
import { Route as AuthenticatedAdminEmulatorsRouteImport } from './routes/_authenticated/admin/emulators'
import { Route as AuthenticatedAdminDevicesRouteImport } from './routes/_authenticated/admin/devices'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated/admin/agents'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin/accounts'
import { Route as AuthenticatedAdminMissionsIndexRouteImport } from './routes/_authenticated/admin/missions/index'
import { Route as ApiPublicAgentRpcRouteImport } from './routes/api/public/agent/rpc'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent/register'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicAgentEventsRouteImport } from './routes/api/public/agent/events'
import { Route as ApiPublicAgentCommandsRouteImport } from './routes/api/public/agent/commands'
import { Route as AuthenticatedAdminMissionsIdRouteImport } from './routes/_authenticated/admin/missions/$id'
import { Route as AuthenticatedAdminMissionsRunsRunIdRouteImport } from './routes/_authenticated/admin/missions/runs/$runId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFarmsIndexRoute = AuthenticatedFarmsIndexRouteImport.update({
  id: '/farms/',
  path: '/farms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicManifestRoute = ApiPublicManifestRouteImport.update({
  id: '/api/public/manifest',
  path: '/api/public/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFarmsIdRoute = AuthenticatedFarmsIdRouteImport.update({
  id: '/farms/$id',
  path: '/farms/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVisionTestRoute =
  AuthenticatedAdminVisionTestRouteImport.update({
    id: '/admin/vision-test',
    path: '/admin/vision-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVisionRoute =
  AuthenticatedAdminVisionRouteImport.update({
    id: '/admin/vision',
    path: '/admin/vision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResourcesRoute =
  AuthenticatedAdminResourcesRouteImport.update({
    id: '/admin/resources',
    path: '/admin/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRecoveryRoute =
  AuthenticatedAdminRecoveryRouteImport.update({
    id: '/admin/recovery',
    path: '/admin/recovery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMonitoringRoute =
  AuthenticatedAdminMonitoringRouteImport.update({
    id: '/admin/monitoring',
    path: '/admin/monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFleetsRoute =
  AuthenticatedAdminFleetsRouteImport.update({
    id: '/admin/fleets',
    path: '/admin/fleets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFarmsRoute = AuthenticatedAdminFarmsRouteImport.update({
  id: '/admin/farms',
  path: '/admin/farms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminEmulatorsRoute =
  AuthenticatedAdminEmulatorsRouteImport.update({
    id: '/admin/emulators',
    path: '/admin/emulators',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDevicesRoute =
  AuthenticatedAdminDevicesRouteImport.update({
    id: '/admin/devices',
    path: '/admin/devices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/admin/agents',
    path: '/admin/agents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/admin/accounts',
    path: '/admin/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMissionsIndexRoute =
  AuthenticatedAdminMissionsIndexRouteImport.update({
    id: '/admin/missions/',
    path: '/admin/missions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAgentRpcRoute = ApiPublicAgentRpcRouteImport.update({
  id: '/api/public/agent/rpc',
  path: '/api/public/agent/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent/register',
  path: '/api/public/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentEventsRoute = ApiPublicAgentEventsRouteImport.update({
  id: '/api/public/agent/events',
  path: '/api/public/agent/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCommandsRoute = ApiPublicAgentCommandsRouteImport.update({
  id: '/api/public/agent/commands',
  path: '/api/public/agent/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminMissionsIdRoute =
  AuthenticatedAdminMissionsIdRouteImport.update({
    id: '/admin/missions/$id',
    path: '/admin/missions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMissionsRunsRunIdRoute =
  AuthenticatedAdminMissionsRunsRunIdRouteImport.update({
    id: '/admin/missions/runs/$runId',
    path: '/admin/missions/runs/$runId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/emulators': typeof AuthenticatedAdminEmulatorsRoute
  '/admin/farms': typeof AuthenticatedAdminFarmsRoute
  '/admin/fleets': typeof AuthenticatedAdminFleetsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vision': typeof AuthenticatedAdminVisionRoute
  '/admin/vision-test': typeof AuthenticatedAdminVisionTestRoute
  '/farms/$id': typeof AuthenticatedFarmsIdRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/farms/': typeof AuthenticatedFarmsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/admin/missions/$id': typeof AuthenticatedAdminMissionsIdRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRoute
  '/api/public/agent/events': typeof ApiPublicAgentEventsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/rpc': typeof ApiPublicAgentRpcRoute
  '/admin/missions/': typeof AuthenticatedAdminMissionsIndexRoute
  '/admin/missions/runs/$runId': typeof AuthenticatedAdminMissionsRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/admin/emulators': typeof AuthenticatedAdminEmulatorsRoute
  '/admin/farms': typeof AuthenticatedAdminFarmsRoute
  '/admin/fleets': typeof AuthenticatedAdminFleetsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vision': typeof AuthenticatedAdminVisionRoute
  '/admin/vision-test': typeof AuthenticatedAdminVisionTestRoute
  '/farms/$id': typeof AuthenticatedFarmsIdRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/farms': typeof AuthenticatedFarmsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/admin/missions/$id': typeof AuthenticatedAdminMissionsIdRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRoute
  '/api/public/agent/events': typeof ApiPublicAgentEventsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/rpc': typeof ApiPublicAgentRpcRoute
  '/admin/missions': typeof AuthenticatedAdminMissionsIndexRoute
  '/admin/missions/runs/$runId': typeof AuthenticatedAdminMissionsRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/devices': typeof AuthenticatedAdminDevicesRoute
  '/_authenticated/admin/emulators': typeof AuthenticatedAdminEmulatorsRoute
  '/_authenticated/admin/farms': typeof AuthenticatedAdminFarmsRoute
  '/_authenticated/admin/fleets': typeof AuthenticatedAdminFleetsRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/monitoring': typeof AuthenticatedAdminMonitoringRoute
  '/_authenticated/admin/recovery': typeof AuthenticatedAdminRecoveryRoute
  '/_authenticated/admin/resources': typeof AuthenticatedAdminResourcesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vision': typeof AuthenticatedAdminVisionRoute
  '/_authenticated/admin/vision-test': typeof AuthenticatedAdminVisionTestRoute
  '/_authenticated/farms/$id': typeof AuthenticatedFarmsIdRoute
  '/api/public/manifest': typeof ApiPublicManifestRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/farms/': typeof AuthenticatedFarmsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/admin/missions/$id': typeof AuthenticatedAdminMissionsIdRoute
  '/api/public/agent/commands': typeof ApiPublicAgentCommandsRoute
  '/api/public/agent/events': typeof ApiPublicAgentEventsRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/agent/register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent/rpc': typeof ApiPublicAgentRpcRoute
  '/_authenticated/admin/missions/': typeof AuthenticatedAdminMissionsIndexRoute
  '/_authenticated/admin/missions/runs/$runId': typeof AuthenticatedAdminMissionsRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tasks'
    | '/admin/accounts'
    | '/admin/agents'
    | '/admin/devices'
    | '/admin/emulators'
    | '/admin/farms'
    | '/admin/fleets'
    | '/admin/logs'
    | '/admin/monitoring'
    | '/admin/recovery'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vision'
    | '/admin/vision-test'
    | '/farms/$id'
    | '/api/public/manifest'
    | '/admin/'
    | '/dashboard/'
    | '/farms/'
    | '/settings/'
    | '/admin/missions/$id'
    | '/api/public/agent/commands'
    | '/api/public/agent/events'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/register'
    | '/api/public/agent/rpc'
    | '/admin/missions/'
    | '/admin/missions/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/tasks'
    | '/admin/accounts'
    | '/admin/agents'
    | '/admin/devices'
    | '/admin/emulators'
    | '/admin/farms'
    | '/admin/fleets'
    | '/admin/logs'
    | '/admin/monitoring'
    | '/admin/recovery'
    | '/admin/resources'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/vision'
    | '/admin/vision-test'
    | '/farms/$id'
    | '/api/public/manifest'
    | '/admin'
    | '/dashboard'
    | '/farms'
    | '/settings'
    | '/admin/missions/$id'
    | '/api/public/agent/commands'
    | '/api/public/agent/events'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/register'
    | '/api/public/agent/rpc'
    | '/admin/missions'
    | '/admin/missions/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/tasks'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/devices'
    | '/_authenticated/admin/emulators'
    | '/_authenticated/admin/farms'
    | '/_authenticated/admin/fleets'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/monitoring'
    | '/_authenticated/admin/recovery'
    | '/_authenticated/admin/resources'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vision'
    | '/_authenticated/admin/vision-test'
    | '/_authenticated/farms/$id'
    | '/api/public/manifest'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/farms/'
    | '/_authenticated/settings/'
    | '/_authenticated/admin/missions/$id'
    | '/api/public/agent/commands'
    | '/api/public/agent/events'
    | '/api/public/agent/heartbeat'
    | '/api/public/agent/register'
    | '/api/public/agent/rpc'
    | '/_authenticated/admin/missions/'
    | '/_authenticated/admin/missions/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicManifestRoute: typeof ApiPublicManifestRoute
  ApiPublicAgentCommandsRoute: typeof ApiPublicAgentCommandsRoute
  ApiPublicAgentEventsRoute: typeof ApiPublicAgentEventsRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicAgentRpcRoute: typeof ApiPublicAgentRpcRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farms/': {
      id: '/_authenticated/farms/'
      path: '/farms'
      fullPath: '/farms/'
      preLoaderRoute: typeof AuthenticatedFarmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/manifest': {
      id: '/api/public/manifest'
      path: '/api/public/manifest'
      fullPath: '/api/public/manifest'
      preLoaderRoute: typeof ApiPublicManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/farms/$id': {
      id: '/_authenticated/farms/$id'
      path: '/farms/$id'
      fullPath: '/farms/$id'
      preLoaderRoute: typeof AuthenticatedFarmsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vision-test': {
      id: '/_authenticated/admin/vision-test'
      path: '/admin/vision-test'
      fullPath: '/admin/vision-test'
      preLoaderRoute: typeof AuthenticatedAdminVisionTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/vision': {
      id: '/_authenticated/admin/vision'
      path: '/admin/vision'
      fullPath: '/admin/vision'
      preLoaderRoute: typeof AuthenticatedAdminVisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/resources': {
      id: '/_authenticated/admin/resources'
      path: '/admin/resources'
      fullPath: '/admin/resources'
      preLoaderRoute: typeof AuthenticatedAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/recovery': {
      id: '/_authenticated/admin/recovery'
      path: '/admin/recovery'
      fullPath: '/admin/recovery'
      preLoaderRoute: typeof AuthenticatedAdminRecoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/monitoring': {
      id: '/_authenticated/admin/monitoring'
      path: '/admin/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AuthenticatedAdminMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/fleets': {
      id: '/_authenticated/admin/fleets'
      path: '/admin/fleets'
      fullPath: '/admin/fleets'
      preLoaderRoute: typeof AuthenticatedAdminFleetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/farms': {
      id: '/_authenticated/admin/farms'
      path: '/admin/farms'
      fullPath: '/admin/farms'
      preLoaderRoute: typeof AuthenticatedAdminFarmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/emulators': {
      id: '/_authenticated/admin/emulators'
      path: '/admin/emulators'
      fullPath: '/admin/emulators'
      preLoaderRoute: typeof AuthenticatedAdminEmulatorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/devices': {
      id: '/_authenticated/admin/devices'
      path: '/admin/devices'
      fullPath: '/admin/devices'
      preLoaderRoute: typeof AuthenticatedAdminDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/missions/': {
      id: '/_authenticated/admin/missions/'
      path: '/admin/missions'
      fullPath: '/admin/missions/'
      preLoaderRoute: typeof AuthenticatedAdminMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/agent/rpc': {
      id: '/api/public/agent/rpc'
      path: '/api/public/agent/rpc'
      fullPath: '/api/public/agent/rpc'
      preLoaderRoute: typeof ApiPublicAgentRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/register': {
      id: '/api/public/agent/register'
      path: '/api/public/agent/register'
      fullPath: '/api/public/agent/register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/events': {
      id: '/api/public/agent/events'
      path: '/api/public/agent/events'
      fullPath: '/api/public/agent/events'
      preLoaderRoute: typeof ApiPublicAgentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/commands': {
      id: '/api/public/agent/commands'
      path: '/api/public/agent/commands'
      fullPath: '/api/public/agent/commands'
      preLoaderRoute: typeof ApiPublicAgentCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/missions/$id': {
      id: '/_authenticated/admin/missions/$id'
      path: '/admin/missions/$id'
      fullPath: '/admin/missions/$id'
      preLoaderRoute: typeof AuthenticatedAdminMissionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/missions/runs/$runId': {
      id: '/_authenticated/admin/missions/runs/$runId'
      path: '/admin/missions/runs/$runId'
      fullPath: '/admin/missions/runs/$runId'
      preLoaderRoute: typeof AuthenticatedAdminMissionsRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminDevicesRoute: typeof AuthenticatedAdminDevicesRoute
  AuthenticatedAdminEmulatorsRoute: typeof AuthenticatedAdminEmulatorsRoute
  AuthenticatedAdminFarmsRoute: typeof AuthenticatedAdminFarmsRoute
  AuthenticatedAdminFleetsRoute: typeof AuthenticatedAdminFleetsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminMonitoringRoute: typeof AuthenticatedAdminMonitoringRoute
  AuthenticatedAdminRecoveryRoute: typeof AuthenticatedAdminRecoveryRoute
  AuthenticatedAdminResourcesRoute: typeof AuthenticatedAdminResourcesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVisionRoute: typeof AuthenticatedAdminVisionRoute
  AuthenticatedAdminVisionTestRoute: typeof AuthenticatedAdminVisionTestRoute
  AuthenticatedFarmsIdRoute: typeof AuthenticatedFarmsIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedFarmsIndexRoute: typeof AuthenticatedFarmsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedAdminMissionsIdRoute: typeof AuthenticatedAdminMissionsIdRoute
  AuthenticatedAdminMissionsIndexRoute: typeof AuthenticatedAdminMissionsIndexRoute
  AuthenticatedAdminMissionsRunsRunIdRoute: typeof AuthenticatedAdminMissionsRunsRunIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminDevicesRoute: AuthenticatedAdminDevicesRoute,
  AuthenticatedAdminEmulatorsRoute: AuthenticatedAdminEmulatorsRoute,
  AuthenticatedAdminFarmsRoute: AuthenticatedAdminFarmsRoute,
  AuthenticatedAdminFleetsRoute: AuthenticatedAdminFleetsRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminMonitoringRoute: AuthenticatedAdminMonitoringRoute,
  AuthenticatedAdminRecoveryRoute: AuthenticatedAdminRecoveryRoute,
  AuthenticatedAdminResourcesRoute: AuthenticatedAdminResourcesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVisionRoute: AuthenticatedAdminVisionRoute,
  AuthenticatedAdminVisionTestRoute: AuthenticatedAdminVisionTestRoute,
  AuthenticatedFarmsIdRoute: AuthenticatedFarmsIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedFarmsIndexRoute: AuthenticatedFarmsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedAdminMissionsIdRoute: AuthenticatedAdminMissionsIdRoute,
  AuthenticatedAdminMissionsIndexRoute: AuthenticatedAdminMissionsIndexRoute,
  AuthenticatedAdminMissionsRunsRunIdRoute:
    AuthenticatedAdminMissionsRunsRunIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicManifestRoute: ApiPublicManifestRoute,
  ApiPublicAgentCommandsRoute: ApiPublicAgentCommandsRoute,
  ApiPublicAgentEventsRoute: ApiPublicAgentEventsRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicAgentRpcRoute: ApiPublicAgentRpcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
